### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by milefxd** [Shadowmaster346/calculator-on-bash#16]
[root@ilya ~]# ./calcd.sh 100 35 +
Small calculator
First number
5
./calcd.sh: line 4: read: `100': not a valid identifier
You First number is 100
Second number
9
./calcd.sh: line 7: read: `35': not a valid identifier
You Second number is 35
+-*/
9
./calcd.sh: line 10: read: `+': not a valid identifier
135

**Comment by Shadowmaster346** [comment]
idk

**Comment by Shadowmaster346** [comment]
i think multi input not supported

**Comment by Shadowmaster346** [comment]
i tomorrow test github workflow

**Comment by Shadowmaster346** [comment]
and them test this again

**Comment by Shadowmaster346** [comment]
but now i delete this branch
